name: Publish latest image
on:
  schedule:
    - cron: 0 0 * * */2
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/delete-package-versions@v3
      with: 
        package-name: "mydockerimage"
        min-versions-to-keep: 10
