name: Publish latest image
on:
  schedule:
    - cron: 0 0 * * */2
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup QEMU to Docker
        uses: docker/setup-qemu-action@v2

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login into registry Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build core image
        uses: docker/build-push-action@v3
        with:
          cache-from: type=gha,scope=sirherobrine23_docker
          cache-to: type=gha,scope=sirherobrine23_docker
          platforms: "linux/amd64,linux/arm64"
          context: ./
          target: core
          push: true
          tags: |
            ghcr.io/sirherobrine23/initjs:core

      - name: Build full image
        uses: docker/build-push-action@v3
        with:
          cache-from: type=gha,scope=sirherobrine23_docker
          cache-to: type=gha,scope=sirherobrine23_docker
          platforms: "linux/amd64,linux/arm64"
          context: ./
          target: full
          push: true
          tags: |
            ghcr.io/sirherobrine23/mydockerimage:latest
            ghcr.io/sirherobrine23/initjs:latest
            ghcr.io/sirherobrine23/initjs:full
