name: Pull request Docker build
on:
  pull_request:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup QEMU to Docker
        uses: docker/setup-qemu-action@v2

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build image
        uses: docker/build-push-action@v3
        with:
          platforms: "linux/amd64"
          context: ./
          tags: sirherobrine23/initjs:latest
          outputs: type=oci,dest=/tmp/image.tar

      - name: "Upload docker image to arctifial"
        uses: actions/upload-artifact@v2
        with:
          name: oci_image
          path: /tmp/image.tar
